### ISSUE TITLE
[Issue]: Productive Bees keep disappearing.

### ISSUE THREAD

**Issue by Fruchtmolke** [The-Nexus-Project/Limitless-5#214] opened 2022-11-10 20:51 UTC
### What happened?

A couple of times most of the bees from productive bees aswell as the vanilla bees are disapperaing.

### Pack Version

Version: 2.26.2

### To Reproduce

1. Happens periodicly. Wild bees disappear aswell as bees kept in buildings.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Anything else to add?

Searched through productive bees wiki but nothing found there. Chunks are loaded and not all of the bees are disappearing. Glowing bee/Ender bee won't disappear.

**Comment by Gbergz** [comment] 2022-11-24 13:30
Hey, still happening?
I can't reproduce this issue.

**Comment by Fruchtmolke** [comment] 2022-11-25 22:38
Hey,

well it happened 2 times. First time after a server restart and the second time after an update + restart. These two times were it happened are in a rare interval (Around 2 month~) so i figured, that it will be hard to reproduce. Since the commit, it hasn't happened again.

**Comment by Fruchtmolke** [comment] 2022-11-26 16:21
Well it happened again today after i made the newest update. Has to do something with updating and restarting the server.

**Comment by Gbergz** [comment] 2022-11-26 16:39
Weird. I've tried that and other stuff.

Bees never seem to despawn, ever. Hm...

**Comment by Gbergz** [comment] 2022-11-26 16:40
Give your bees all name tags. See if it changes anything.

**Comment by Fruchtmolke** [comment] 2022-11-26 16:42
A freind of mine on the server put some nametags on bees. Like 2 or 3 bees. But they disappeared aswell.

**Comment by Gbergz** [comment] 2022-11-26 16:48
No idea then.

**Comment by JaisDK** [comment] 2022-11-26 16:53
Your server is not shutting down correctly. This can cause bees to disappear or duplicate depending on when they left or entered a hive. It happens more often for chunkloaded bees because they are always loaded when the incorrect shutdown occurs. There's nothing for me to do about it, you have to figure out why your server is not shutting down correctly (usually it's a mod that won't release a thread)

**Comment by JaisDK** [comment] 2022-11-26 16:55
to check if the server shut down correctly, you have to look at the end of the log file and find this

```
[25Nov2022 23:40:56.107] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[25Nov2022 23:40:56.108] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[25Nov2022 23:40:56.109] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[25Nov2022 23:40:58.970] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[25Nov2022 23:41:00.814] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[25Nov2022 23:41:00.870] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[25Nov2022 23:41:00.941] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (world): All chunks are saved
[25Nov2022 23:41:00.942] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[25Nov2022 23:41:00.942] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[25Nov2022 23:41:00.943] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
```

if the lines about having saved the chunk are missing, it was not a correct shutdown and you've lost data

**Comment by Gbergz** [comment] 2022-11-29 20:26
Closing but feel free to continue to discuss in here.

**Closed by Gbergz** 2022-11-29 20:26 UTC
Labels: can't reproduce issue, issue

**Comment by JaisDK** [comment] 2022-12-01 09:48
Forgot to mention that to prevent it from happening again you can use simulated hives instead. When the bees don't leave the hive there won't be a save discrepancy. Check the guide book for how to use the sim upgrade.
