### ISSUE TITLE
Machines not working like intended

### ISSUE THREAD

**Issue by rVanix** [The-Nexus-Project/Limitless-5#93] opened 2022-06-04 10:59 UTC
### Are you using OptiFine?
yes I am, but it doesn't work without it either.

### Describe your issue, what happened?
I updated the modpack version and tried loading into the same world and many issues occurred.
I was able to fix some, but there are still 2 more left.

The first one is that the solar neutron activator isn't processing the nuclear waste anymore.
I tried moving them and setting up new once but they won't do anything. 
I tried the exact same thing in a new world, but they still didn't work.

The second thing is that all the crops from mystical agriculture despawned and I can't replace them it's like there is no farmland.
And same thing as before there is no way of fixing it not even when I try the exact same thing in a new world.

And one extra thing, my Refined storage system is at it max energy consumption and when I want to connect one more thing to it it keeps shutting down and back up again over and over again so I wanted to change the max allowed energy consumption in the config files but wasn't able to find the config files.
Would be nice if I could change that it currently caps at around 16krf/t 

### To Reproduce
Update to modpack version 2.8.2 and launch into and existing world

### Expected behavior
I want the solar neutron activator to process the nuclear waste into polonium.
And I want the Mystical Agriculture seeds to be plantable again.
Also would be nice if I can change the max energy consumption of my Refined storage system to be higher

### Screenshots
![image](https://user-images.githubusercontent.com/87763808/171996000-a3854f70-b55a-4e1a-b6fe-c7230980dcdd.png)

### Affected Version
modpack version 2.8.2

**Comment by rVanix** [comment] 2022-06-04 11:04
And one last thing which I forgot is, when I press ctr and space at the same time when flying with the meka suit I keep flying forward. That also changed when I updated the version and it is really annoying when I try placing blocks somewhere and I keep flying forward.

**Comment by Gbergz** [comment] 2022-06-04 11:30
Thanks for report.

**Comment by Gbergz** [comment] 2022-06-04 14:33
> The first one is that the solar neutron activator isn't processing the nuclear waste anymore.
I tried moving them and setting up new once but they won't do anything.
I tried the exact same thing in a new world, but they still didn't work.

Tried this, can't reproduce, it's working like normally in my Singleplayer world & on the official servers.

> The second thing is that all the crops from mystical agriculture despawned and I can't replace them it's like there is no farmland.
And same thing as before there is no way of fixing it not even when I try the exact same thing in a new world.

And this I also couldn't reproduce.
Have to ask though if this is in the Mining Dimension perhaps? It's a known issue stuff not working there correctly at the moment but will be fixed for the next update.

> And one last thing which I forgot is, when I press ctr and space at the same time when flying with the meka suit I keep flying forward.

Can't reproduce this either.

**Comment by rVanix** [comment] 2022-06-04 15:41
Yeah it's in the mining dimension
So it gets fixed in the next modpack update or a mod update?

**Comment by Gbergz** [comment] 2022-06-04 15:45
Next modpack update (v2.9.0) as of now.

**Comment by rVanix** [comment] 2022-06-04 15:46
Ok thank you!

**Comment by rVanix** [comment] 2022-06-04 15:49
Oh and what about the refined storage energy consumption and the meka suit forward flying thing?

**Comment by Gbergz** [comment] 2022-06-04 15:51
No idea, can't reproduce either.

**Comment by rVanix** [comment] 2022-06-04 15:52
Ok strange thanks anyway

**Comment by Gbergz** [comment] 2022-06-09 21:07
v2.9.0 fixes mining dim issues

**Closed** 2022-06-09 21:06 UTC
