### ISSUE TITLE
Duping Bug With Refined Storage Crafting Grid [Issue] 

### ISSUE THREAD

**Issue by crimsonsunny** [The-Nexus-Project/Limitless-5#84] opened 2022-05-26 19:39 UTC
### Describe your issue, what happened?
When using the crafting grid from Refined Storage, if you use the engineer's hammer from Immersive Engineering with any raw ores (i.e. raw Osmium, raw iron, raw gold, raw crimson iron) to create dusts, you can duplicate up to a stack of dusts from a single craft (which should only yield 2 dusts per craft) as long as the hammer has durability and the raw ore used does not run out. Once you alter the crafting recipe in any way once the duping glitch is performed, the duping glitch stops. Additionally, once you do the crafting dupe, it permanently glitches out the dust crafting recipe with the engineer's hammer (you can no longer make any crafts with the hammer + that specific raw ore). 

### To Reproduce
1. Craft Engineer's Hammer from Immersive Engineering.
2. Get a stack of any raw ore (i.e. raw iron, raw copper).
3. Use the Crafting Grid from Refined Storage and create the recipe for ore dusts (hammer + any raw ore).
4. Click extremely fast on the crafting output, until it reaches 64.
5. Once you have 64 dusts in the crafting output, put the ore dusts into the Refined Storage system. If you put the duped ore dusts into your inventory, it ends the duping glitch. 
6. You can now keep clicking the crafting output (a stack of 64 dusts) for as long as the hammer has durability and the stock of raw ore in the Refined Storage system does not run out. 
7. Once you alter the recipe in any way, the recipe using the hammer + any raw ore is permanently glitched out for that particular ore. 

### Expected behavior

Normally, you are able to click extremely fast (not shift-click) on the crafting output to make multiple crafts - I wanted to make 16 tin dust using raw tin and an engineer's hammer. Normally, I expect clicking 8 times on the output to yield 8x2 dusts = 16 dusts. 

### Screenshots

![image](https://user-images.githubusercontent.com/76500536/170563039-8da33845-a895-486b-a01a-49001b8ff379.png)
![image](https://user-images.githubusercontent.com/76500536/170563094-3d437139-0bbe-43d7-a8f6-c52ac2f34c61.png)

### Affected Version

- Pack Version: 2.7.0
- On a server?: Yes

**Comment by shinji257** [comment] 2022-05-26 21:58
I was able to reproduce this with Tom's Simple Storage as well so it isn't exclusive to Refined Storage.

**Comment by Gbergz** [comment] 2022-05-26 22:03
Investigating. I would recommend not using a dupe. But ofcourse that is up to you.

**Comment by crimsonsunny** [comment] 2022-05-26 22:16
Was able to reproduce this bug on other mods, including Integrated Dynamics and Crafting Station (from tinkers). 

Additionally, tested with AE2 and Mekanism's QIO, and they did not have this bug.

**Comment by shinji257** [comment] 2022-05-26 22:30
Related bug report on Immersive Engineering:
https://github.com/BluSunrize/ImmersiveEngineering/issues/5275

**Comment by Gbergz** [comment] 2022-06-09 21:08
This issue is fixed in IE's newest update, will include it in the next modpack update.

**Closed by Gbergz** 2022-06-09 21:08 UTC
Labels: known issue, Investigating
