### ISSUE TITLE
[Issue]: Blue Skies Alchemy table doesn't let you get stripped logs

### ISSUE THREAD

**Issue by jinkhya** [The-Nexus-Project/Limitless-5#127] opened 2022-07-13 15:38 UTC
### What happened?

This is probably gonna be hard to find where the issue comes from but the alchemy table from Blue skies doesn't work if you try to get stripped logs. The normal logs seem to work. 
I have tried an instance with just Blue skies and I could get the stripped logs just fine so there must be a mod interfering in limitless V.

### Pack Version

Version: 2.14.0

### To Reproduce

1. Place an alchemy table from Blue skies 
2. Open it and place some logs in it 
3. try to get any stripped logs

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by jinkhya** [comment] 2022-07-13 15:56
Mh I'll have to investigate some more then. For me when I click on the result log it doesn't give me anything. The ingredient disappears for half a second like it was used and then comes back to its slot because it didn't craft into anything

**Comment by jinkhya** [comment] 2022-07-13 16:35
Oh, it works in SP but not server, you're testing in SP right?

**Comment by Gbergz** [comment] 2022-07-13 16:52
Yes I was testing in SP.
But I had a player on the official server for LL5 test if it works on a server and it did.

**Comment by newtrogicNexus** [comment] 2022-07-13 20:07
Actually, yeah, I've had the same issue. It seems like materials in the alchemy table too far down the list just don't work.

**Comment by Gbergz** [comment] 2022-07-13 20:08
> Actually, yeah, I've had the same issue. It seems like materials in the alchemy table too far down the list just don't work, no matter what type it is.

Can't reproduce it still. Everything works. SP & Server.

**Comment by TopPercentageRattata** [comment] 2022-07-14 22:23
For me, some log types don't work, and some give completely wrong results. Anything past Stripped Sortingwood and Stripped Spruce Logs have the wood types give the START of the table outputs again. For example. Acacia beam is the first output in the alchemy table, and Stripped Spruce wood starts giving acacia beam again. 
Attached is first log output working, and then an example of a the output types restarting from the top
![2022-07-14_17 18 57](https://user-images.githubusercontent.com/16669193/179098471-48d977e7-50fb-426b-86be-e3fcc7940438.png)
![2022-07-14_17 18 50](https://user-images.githubusercontent.com/16669193/179098480-48e09f78-a716-43d4-a9ee-a6d0daf9b540.png)
![2022-07-14_17 18 42](https://user-images.githubusercontent.com/16669193/179098486-0757480e-acf9-437f-8009-180b6b4e9721.png)
.

**Comment by TopPercentageRattata** [comment] 2022-07-14 22:25
Wool also has the same issue where it resets back to black wool after chipped:red_wool_17
Guessing Alchemy table wasn't designed for such a huge variety of outputs

**Comment by Gbergz** [comment] 2022-07-18 10:17
Closing this as it seems it works sometimes and sometimes not, not really sure I can fix it.
Thanks for reports though.

**Closed by Gbergz** 2022-07-18 10:17 UTC
Labels: can't reproduce issue, issue
