### ISSUE TITLE
Login issue, crashed upon using a grave key to get back to a grave with a boss mob enderman at it

### ISSUE THREAD

**Issue by Etroll780** [The-Nexus-Project/Limitless-5#2] opened 2021-12-16 02:08 UTC
[21:05:32] [Server thread/INFO]: Syncing config to Quarkee _(idk if this id is sensitive info)_
[21:05:32] [Server thread/INFO]: Login detected, adding player to logins for defuzz.
[21:05:34] [Server thread/INFO]: No entity was found
[21:05:34] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2434ms or 48 ticks behind
[21:05:34] [Netty Epoll Server IO #2/ERROR]: Error encoding packet
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "p_130073_" is null
	at net.minecraft.network.FriendlyByteBuf.m_130072_(FriendlyByteBuf.java:507) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.FriendlyByteBuf.m_130070_(FriendlyByteBuf.java:503) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.syncher.EntityDataSerializers$4.m_6856_(EntityDataSerializers.java:66) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.syncher.EntityDataSerializers$4.m_6856_(EntityDataSerializers.java:64) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.syncher.SynchedEntityData.m_135367_(SynchedEntityData.java:195) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.syncher.SynchedEntityData.m_135358_(SynchedEntityData.java:139) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.m_5779_(ClientboundSetEntityDataPacket.java:34) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:42) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:15) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at net.minecraft.network.Connection.m_178303_(Connection.java:202) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.Connection.lambda$sendPacket$5(Connection.java:191) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[21:05:34] [Netty Epoll Server IO #2/ERROR]: Error encoding packet
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "p_130073_" is null
	at net.minecraft.network.FriendlyByteBuf.m_130072_(FriendlyByteBuf.java:507) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.FriendlyByteBuf.m_130070_(FriendlyByteBuf.java:503) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.syncher.EntityDataSerializers$4.m_6856_(EntityDataSerializers.java:66) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.syncher.EntityDataSerializers$4.m_6856_(EntityDataSerializers.java:64) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.syncher.SynchedEntityData.m_135367_(SynchedEntityData.java:195) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.syncher.SynchedEntityData.m_135358_(SynchedEntityData.java:139) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.m_5779_(ClientboundSetEntityDataPacket.java:34) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:42) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:15) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at net.minecraft.network.Connection.m_178303_(Connection.java:202) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at net.minecraft.network.Connection.lambda$sendPacket$5(Connection.java:191) ~[server-1.18.1-20211210.034407-srg.jar%23227!:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[21:05:34] [Server thread/INFO]: Quarkee lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "p_130073_" is null

**Comment by Gbergz** [comment] 2021-12-19 15:49
Hm, weird. Can't reproduce this. Is this still happening on newer pack versions?

**Comment by Gbergz** [comment] 2021-12-24 16:39
Closing. Re-open if you find anything.

**Closed by Gbergz** 2021-12-24 16:39 UTC
