### ISSUE TITLE
[Issue]: Container Mouseover disconnects 

### ISSUE THREAD

**Issue by nottah** [The-Nexus-Project/Limitless-5#182] opened 2022-09-06 16:48 UTC
### What happened?

Enjoying the pack after installing a fresh copy of the newest release 2.20.1
 Running smooth until opening a chest in a particular house. have replicated several times. Once I am booted or lost connection I get a java socket error and timed out message trying to reconnect. Ill drop the log if it helps.
 Server log attached
[crash-2022-09-06_11.44.09-server.txt](https://github.com/The-Nexus-Project/Limitless-5/files/9499029/crash-2022-09-06_11.44.09-server.txt)
Player Log attached
[2022-09-06-5.log](https://github.com/The-Nexus-Project/Limitless-5/files/9499037/2022-09-06-5.log)

### Pack Version

Version: server 2.20.2
client is the same

### To Reproduce

1.Login and play normally , working fine. traverse to the house in a deserted village. One house has the chest that disconnects me.
one other house across from it I can loot the chest just fine.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Anything else to add?

Update: It turns out the whole house is bugged, as in all containers do not show the description when moused over. Only The walls and building material show up when looking at it. If that makes any sense. I went back inside and did not open anything and moused over all containers and it booted me. So basically it showed the items but it wasn't there?

I have decided to make a new server and keep this one offline in case someone needs first hand experience for the issue.

**Comment by Gbergz** [comment] 2022-09-06 16:50
Watchdog crashes are annoying as they do not contain many indications on what the issue could be. Pretty sure this issue has been reported already in our discord and I've got no clue what it is and what it's caused by.

But thanks for the report.

**Comment by nottah** [comment] 2022-09-06 16:53
Thank you.  I will be making a new server in case it was just worldgen issue. I will keep the old server in case it needs to be investigated. We just started so no real loss.

**Comment by Gbergz** [comment] 2022-09-09 19:51
This should be fixed in 2.20.2.

**Closed by Gbergz** 2022-09-09 19:51 UTC
Labels: Server Watchdog, issue
